# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/karthik/Computers/tchecker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/karthik/Computers/tchecker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karthik/Computers/tchecker/CMakeFiles /home/karthik/Computers/tchecker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karthik/Computers/tchecker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libtchecker_static

# Build rule for target.
libtchecker_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libtchecker_static
.PHONY : libtchecker_static

# fast build rule for target.
libtchecker_static/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/libtchecker_static.dir/build.make src/CMakeFiles/libtchecker_static.dir/build
.PHONY : libtchecker_static/fast

#=============================================================================
# Target rules for targets named tchecker

# Build rule for target.
tchecker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tchecker
.PHONY : tchecker

# fast build rule for target.
tchecker/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/tchecker.dir/build.make src/CMakeFiles/tchecker.dir/build
.PHONY : tchecker/fast

#=============================================================================
# Target rules for targets named program_parsing_static

# Build rule for target.
program_parsing_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 program_parsing_static
.PHONY : program_parsing_static

# fast build rule for target.
program_parsing_static/fast:
	$(MAKE) $(MAKESILENT) -f src/parsing/program_parser/CMakeFiles/program_parsing_static.dir/build.make src/parsing/program_parser/CMakeFiles/program_parsing_static.dir/build
.PHONY : program_parsing_static/fast

#=============================================================================
# Target rules for targets named system_parsing_static

# Build rule for target.
system_parsing_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 system_parsing_static
.PHONY : system_parsing_static

# fast build rule for target.
system_parsing_static/fast:
	$(MAKE) $(MAKESILENT) -f src/parsing/system_parser/CMakeFiles/system_parsing_static.dir/build.make src/parsing/system_parser/CMakeFiles/system_parsing_static.dir/build
.PHONY : system_parsing_static/fast

#=============================================================================
# Target rules for targets named save

# Build rule for target.
save: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 save
.PHONY : save

# fast build rule for target.
save/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/save.dir/build.make test/CMakeFiles/save.dir/build
.PHONY : save/fast

#=============================================================================
# Target rules for targets named testutils

# Build rule for target.
testutils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testutils
.PHONY : testutils

# fast build rule for target.
testutils/fast:
	$(MAKE) $(MAKESILENT) -f test/testutils/CMakeFiles/testutils.dir/build.make test/testutils/CMakeFiles/testutils.dir/build
.PHONY : testutils/fast

#=============================================================================
# Target rules for targets named bug-007-bin

# Build rule for target.
bug-007-bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bug-007-bin
.PHONY : bug-007-bin

# fast build rule for target.
bug-007-bin/fast:
	$(MAKE) $(MAKESILENT) -f test/bugfixes/CMakeFiles/bug-007-bin.dir/build.make test/bugfixes/CMakeFiles/bug-007-bin.dir/build
.PHONY : bug-007-bin/fast

#=============================================================================
# Target rules for targets named save-bugfixes

# Build rule for target.
save-bugfixes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 save-bugfixes
.PHONY : save-bugfixes

# fast build rule for target.
save-bugfixes/fast:
	$(MAKE) $(MAKESILENT) -f test/bugfixes/CMakeFiles/save-bugfixes.dir/build.make test/bugfixes/CMakeFiles/save-bugfixes.dir/build
.PHONY : save-bugfixes/fast

#=============================================================================
# Target rules for targets named save-simple-nr

# Build rule for target.
save-simple-nr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 save-simple-nr
.PHONY : save-simple-nr

# fast build rule for target.
save-simple-nr/fast:
	$(MAKE) $(MAKESILENT) -f test/simple-nr/CMakeFiles/save-simple-nr.dir/build.make test/simple-nr/CMakeFiles/save-simple-nr.dir/build
.PHONY : save-simple-nr/fast

#=============================================================================
# Target rules for targets named save-covreach

# Build rule for target.
save-covreach: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 save-covreach
.PHONY : save-covreach

# fast build rule for target.
save-covreach/fast:
	$(MAKE) $(MAKESILENT) -f test/covreach/CMakeFiles/save-covreach.dir/build.make test/covreach/CMakeFiles/save-covreach.dir/build
.PHONY : save-covreach/fast

#=============================================================================
# Target rules for targets named save-explore

# Build rule for target.
save-explore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 save-explore
.PHONY : save-explore

# fast build rule for target.
save-explore/fast:
	$(MAKE) $(MAKESILENT) -f test/explore/CMakeFiles/save-explore.dir/build.make test/explore/CMakeFiles/save-explore.dir/build
.PHONY : save-explore/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... save"
	@echo "... save-bugfixes"
	@echo "... save-covreach"
	@echo "... save-explore"
	@echo "... save-simple-nr"
	@echo "... bug-007-bin"
	@echo "... libtchecker_static"
	@echo "... program_parsing_static"
	@echo "... system_parsing_static"
	@echo "... tchecker"
	@echo "... testutils"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

