# CMake generated Testfile for 
# Source directory: /home/karthik/Computers/tchecker/test/bugfixes
# Build directory: /home/karthik/Computers/tchecker/test/bugfixes
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bug-002 "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-002 PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-002.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-002.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-002.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-002.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/src/tchecker;TEST_ARGS=explore -f raw -m ta /home/karthik/Computers/tchecker/test/bugfixes/bug-002.tck" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-003a "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-003a PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-003a.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-003a.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-003a.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-003a.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/src/tchecker;TEST_ARGS=explore -f raw -m ta /home/karthik/Computers/tchecker/test/bugfixes/bug-003a.tck" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-003b "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-003b PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-003b.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-003b.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-003b.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-003b.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/src/tchecker;TEST_ARGS=explore -f raw -m ta /home/karthik/Computers/tchecker/test/bugfixes/bug-003b.tck" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-004 "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-004 PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-004.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-004.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-004.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-004.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/test/bugfixes/bug-004.sh" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-005a "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-005a PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005a.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005a.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005a.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005a.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/test/bugfixes/bug-005a.sh" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-005b "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-005b PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005b.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005b.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005b.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005b.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/test/bugfixes/bug-005b.sh" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-005c "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-005c PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005c.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005c.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005c.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-005c.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/test/bugfixes/bug-005c.sh" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-007 "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-007 PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-007.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-007.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-007.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-007.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/test/bugfixes/bug-007-bin" FIXTURES_REQUIRED "BUILD_bug-007-bin;BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-007-bin-build "/usr/bin/cmake" "--build" "/home/karthik/Computers/tchecker" "--config" "Release" "--target" "bug-007-bin")
set_tests_properties(bug-007-bin-build PROPERTIES  FIXTURES_SETUP "BUILD_bug-007-bin" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;193;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;220;add_testbin_target_;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-008a "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-008a PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-008a.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-008a.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-008a.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-008a.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/test/bugfixes/bug-008a.sh" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-008b "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-008b PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-008b.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-008b.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-008b.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-008b.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/test/bugfixes/bug-008b.sh" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-009 "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-009 PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-009.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-009.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-009.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-009.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/src/tchecker;TEST_ARGS=explore -f raw -m ta /home/karthik/Computers/tchecker/test/bugfixes/bug-009.tck" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(bug-041 "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(bug-041 PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-041.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-041.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-041.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/bug-041.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/test/bugfixes/bug-041.sh" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
add_test(memleak-01 "/home/karthik/Computers/tchecker/test/test-driver.sh")
set_tests_properties(memleak-01 PROPERTIES  ENVIRONMENT "INPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_DIR=/home/karthik/Computers/tchecker/test/bugfixes;OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/memleak-01.out;ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/memleak-01.err;EXPECTED_OUTPUT_FILE=/home/karthik/Computers/tchecker/test/bugfixes/memleak-01.out-expected;EXPECTED_ERROR_FILE=/home/karthik/Computers/tchecker/test/bugfixes/memleak-01.err-expected;SRCDIR=/home/karthik/Computers/tchecker/test/bugfixes;TCK_EXAMPLES_DIR=/home/karthik/Computers/tchecker/examples;TCHECKER=/home/karthik/Computers/tchecker/src/tchecker;TEST=/home/karthik/Computers/tchecker/src/tchecker;TEST_ARGS=explore -f raw -m ta /home/karthik/Computers/tchecker/test/bugfixes/memleak-01.tck" FIXTURES_REQUIRED "BUILD_TCHECKER" WORKING_DIRECTORY "/home/karthik/Computers/tchecker/test/bugfixes" _BACKTRACE_TRIPLES "/home/karthik/Computers/tchecker/test/TestUtils.cmake;88;add_test;/home/karthik/Computers/tchecker/test/TestUtils.cmake;212;tck_add_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;29;tck_add_nr_test;/home/karthik/Computers/tchecker/test/bugfixes/CMakeLists.txt;0;")
